### PR TITLE
Gitlab 8x + merged all existing pull request

### PR DESCRIPTION
**Pull request by epcim**
Hi, 
* I merged the pull requests available like week ago (tell me if that is a bad practice for PR)
* Updated all gitlab configurations that required an change to be compliant with gitlab 8.0.4 configuration. As suggested here: http://doc.gitlab.com/ce/update/7.14-to-8.0.html#install-gitlab-git-http-server. 
* In my environment I successfully upgraded from 7.7 to 8.0.4

It's tested. However tonight I will run "kitchen verify" for all platforms to make sure I did not introduced any error and didn't forgot any steps.

I am proposing an merge to master branch. Will appreciate if @atomic-penguin will make final merge.   Please make your comments and suggestions for possible re-bundle.

### CODE REVIEW

**Comment by atomic-penguin** [comment]
> I merged the pull requests available like week ago (tell me if that is a bad practice for PR)

@epcim If it works, (tests pass), then its not a bad practice.  If I have to spend a day going through git bisect, then it might be a problem.

> It's tested. However tonight I will run "kitchen verify" for all platforms to make sure I did not introduced any error and didn't forgot any steps.

If you get a clear bill of health from test-kitchen, fixing the travis build to pass should be trivial.  It looks like the travis.yml file might need updated.

**Comment by epcim** [comment]
Food critics fixed in my branch. Will run "kitchen verify" for all tonight (finally).

**Comment by epcim** [comment]
OK, branch 8x passing `kitchen verify` tests. Feel free to merge PR (I actually has rights to do so, since last time, but prefer this time @atomic-penguin to check README/CHANGELOG whether it's correct.

**Comment by chewi** [comment]
Awesome. :+1:

I've since realised my SELinux stuff fell slightly short as the logrotate stuff isn't playing nicely. I'll hopefully file another pull request soon.

**Pull request merged**
