### PR TITLE
Bugfix 7-7 issues

### PR DESCRIPTION
**Pull request by jeremyolliver**
Cheers, for getting the 7-7 support branch, and other PR's merged.
I found a few other minor changes required to get a full converge in test-kitchen on ubuntu-14.04

### CODE REVIEW

**Comment by atomic-penguin** [comment]
Cheers to both you, and @epcim, for working on this.  I have a very limited amount of time I can work on this.

**Comment by atomic-penguin** [comment]
I'm not getting a full converge on this yet.  Converge problems with mysql cookbook and its dependencies.

**Comment by jeremyolliver** [comment]
There were a couple of manual attributes I ha to add in, but seemed
specific to my vagrant box so I didn't include them. Gitlab MySQL host
needed to be set to 127.0.0.1 so it didn't try ipv6 by default, and I
needed to set build-essential compile_time to true.

Cheers,
Jeremy

On Thursday, February 5, 2015, Eric G. Wolfe <notifications@github.com>
wrote:

> I'm not getting a full converge on this yet. Converge problems with mysql
> cookbook and its dependencies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atomic-penguin/cookbook-gitlab/pull/89#issuecomment-72967778>
> .
>


-- 
Jeremy Olliver

**Comment by atomic-penguin** [comment]
@jeremyolliver if you could, add whatever attributes you needed set to get a `kitchen test` working on the platform you tested on, and I'll backfill compatibility for any remaining platforms.

**Comment by jeremyolliver** [comment]
@atomic-penguin I've just this afternoon added in those last few changes into master, as they did seem necessary enough to add into the cookbooks attributes, rather than just the test-kitchen run. test-kitchen is converging for me cleanly on ubuntu 14.04 now, with no local modifications, and latest cookbooks (also fixed a few breakages from database/mysql cookbook releases last couple of days)

**Comment by jeremyolliver** [comment]
If anything I committed looks odd, or you have questions, ping me tomorrow on irc#chef or flick me an email

**Pull request merged**
