### PR TITLE
LDAP Parameters on gitlab.yml.erb

### PR DESCRIPTION
**Pull request by otaviof**
Small correction on gitlab.yml template logic, where if either :password or :bind_dn is empty or it starts with "_" then it will be commented out.

### CODE REVIEW

**Comment by otaviof** [comment]
Hey Folks, any remarks on this PR? Let me know, please. :-)

**Comment by MichaelKueller** [comment]
I came accross the same error, please merge this pull request.

**Comment by otaviof** [comment]
Including a few more features here. Custom URL for gitlab-shell and Unicorn timeout.

**Comment by MichaelKueller** [comment]
what about merging this PR?

**Comment by atomic-penguin** [comment]
@otaviof & @MichaelKueller sorry for the delay, have just been busy.  Code looks good.  @otaviof can you add some attribute documentation for any added attributes?  I want to make sure we do not have attribute creep, and a good way to avoid that is having well defined attributes.

**Comment by otaviof** [comment]
Hey @atomic-penguin, thanks for the info. And indeed, missing documentation for the added attributes, now it's in place. Let me know if any more changes should take place.

**Comment by atomic-penguin** [comment]
@otaviof so is this really necessary to have a third hostname attribute, or is this more of a case of the attribute name `web_fqdn` is somewhat ambiguous when applied to something like gitlab-shell?  I don't want to make the precedence of attribute selection, and the data structures themselves, more convoluted than they actually need to be.

**Comment by otaviof** [comment]
@atomic-penguin How do you suggest to set this attribute? In my use case I need to set-up gitlab-shell URL separately, and I tried to follow the other examples I found on the cookbook. Thanks in advance.

**Pull request closed without merging**
